### ISSUE TITLE
Throttler - Lock Wait Timeout should Retry

### ISSUE THREAD

**Issue by dfelton** [dfelton/kobens-core#6]
Under certain circumstances the Throttler encounters lock wait timeout issues. Today this is mainly due to shutting the lid of the laptop while running the app in my sandbox environment, which is not a production applicable scenario (or at least shouldn't be).

However I can potentially see this issue occurring in production for other reasons, with enough concurrent threads running. In such an event, the Exception being thrown should ideally be caught by Throttler, and instructed to then retry.

With this enhancement, be sure to implement a max attempts, and throw our own more localized exception in the event of eventual failure.

```
Shutdown Enabled at: 2019-12-23 14:46:51
Exception: Zend\Db\Adapter\Exception\InvalidQueryException
Code: 0
Message: Statement could not be executed (HY000 - 1205 - Lock wait timeout exceeded; try restarting transaction)
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(27): Zend\Db\Adapter\Adapter->query('SELECT * FROM `...', Array)
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(43): Kobens\Core\Http\Request\Throttler->fetchForUpdate()
#3 src/Api/Rest/AbstractRequest.php(74): Kobens\Core\Http\Request\Throttler->throttle()
#4 src/Api/Rest/AbstractRequest.php(60): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#5 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(63): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#6 src/Command/Command/TradeRepeater/Seller.php(127): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '0.1975', '6929.00', 'repeater_77_sel...')
#7 src/Command/Command/TradeRepeater/Seller.php(104): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(ArrayObject), 'repeater_77_sel...')
#8 src/Command/Command/TradeRepeater/Seller.php(77): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Application.php(932): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(274): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(150): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 bin/gemini(229): Symfony\Component\Console\Application->run()
#14 {main}

Previous Exception:
Exception: PDOException
Code: HY000
Message: SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction
Strace:
#0 vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute()
#1 vendor/zendframework/zend-db/src/Adapter/Adapter.php(200): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(27): Zend\Db\Adapter\Adapter->query('SELECT * FROM `...', Array)
#3 vendor/kobens/kobens-core/src/Http/Request/Throttler.php(43): Kobens\Core\Http\Request\Throttler->fetchForUpdate()
#4 src/Api/Rest/AbstractRequest.php(74): Kobens\Core\Http\Request\Throttler->throttle()
#5 src/Api/Rest/AbstractRequest.php(60): Kobens\Gemini\Api\Rest\AbstractRequest->_getResponse()
#6 src/Api/Rest/PrivateEndpoints/OrderPlacement/NewOrder/ForceMaker.php(63): Kobens\Gemini\Api\Rest\AbstractRequest->getResponse()
#7 src/Command/Command/TradeRepeater/Seller.php(127): Kobens\Gemini\Api\Rest\PrivateEndpoints\OrderPlacement\NewOrder\ForceMaker->place(Object(Kobens\Gemini\Exchange\Currency\Pair), 'sell', '0.1975', '6929.00', 'repeater_77_sel...')
#8 src/Command/Command/TradeRepeater/Seller.php(104): Kobens\Gemini\Command\Command\TradeRepeater\Seller->place(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(ArrayObject), 'repeater_77_sel...')
#9 src/Command/Command/TradeRepeater/Seller.php(77): Kobens\Gemini\Command\Command\TradeRepeater\Seller->mainLoop(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 vendor/symfony/console/Command/Command.php(255): Kobens\Gemini\Command\Command\TradeRepeater\Seller->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 vendor/symfony/console/Application.php(932): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 vendor/symfony/console/Application.php(274): Symfony\Component\Console\Application->doRunCommand(Object(Kobens\Gemini\Command\Command\TradeRepeater\Seller), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 vendor/symfony/console/Application.php(150): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 bin/gemini(229): Symfony\Component\Console\Application->run()
#15 {main}
```

**Comment by dfelton** [comment]
Forgot to "use more localized exception", re-opening ticket.
